name: Deploy app to GH Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Fetch Current Repo
      uses: actions/checkout@v2

    - name: npm install, build, and deploy
      run: |
        npm install
        npm run build
        git subtree push --prefix pages origin gh-pages
